### ISSUE TITLE
Can the deep link provided by this plugin register just during installation?

### ISSUE THREAD

**Issue by huangjj27** [FabianLars/tauri-plugin-deep-link#13]
I want to register the deep link operation during the installation, and I check the code of the plugin and find out that it registers the deep link operation during runtime, which means  I have to run my app at least once before using the deep link, so here comes the question.

**Comment by madaster97** [comment]
Hi there,

This plugin is only doing one half of the full "deep linking" workflow. What you're asking for can definitely be done at install time, using a wix template like the one someone put together [here](https://github.com/tauri-apps/tauri/issues/323#issuecomment-920928947). That template is what allows a custom URI scheme like "my-app://launch" to actually launch your application on windows.

What this plugin does is the second half of the problem, which is what happens AFTER you launch "my-app://launch"? This plugin allows new instances of your application to talk to existing instances, which is needed for OAuth 2.0 flows where there is a handshake between your app, another app, and back to your app.

So if your use case does not require communicating between different instances of your app, and just requires custom URI schemes to launch the app, that's totally doable without this plugin.

**Comment by FabianLars** [comment]
> What this plugin does is the second half of the problem, which is what happens AFTER you launch "my-app://launch"?

The plugin indeed does _both_ parts (registering the schemes and handling the events). but as huangjj27 said, it registers the uri schemes only at runtime. This is by design for 3 reasons:
1) There is no installation step where you could register the schemes on Linux and macos and i wanted to keep it as similar as possible.
2) Registering it at runtime makes it usable in portable executables (until the user moves the executable of course)
3) The most important part: I can't change the wix config/template or add fragments from within the plugin, though i did have plans to add a copy-pastable solution for this but never got around doing it.

**Comment by huangjj27** [comment]
@madaster97, @FabianLars, thanks both of you! 

> What you're asking for can definitely be done at install time, using a wix template like the one someone put together https://github.com/tauri-apps/tauri/issues/323#issuecomment-920928947.

Indeed, I'm using the solution above and fixing the multi-window issue with [tauri-plugin-single-instance](https://github.com/amrbashir/tauri-plugin-single-instance). However, by applying these solutions, I have to provide a command to make the parsing available for the frontend, while I just want to keep the parsing work only available in the backend, as the parsing is done at the setup once. Therefore, I came here to find out another solution, but it seems not to meet my requirements.
