### ISSUE TITLE
App doesn't open when there's no running instance

### ISSUE THREAD

**Issue by AmyrAhmady** [FabianLars/tauri-plugin-deep-link#51]
Hi, I've added this plugin to my project and it works perfectly fine ***if*** there's a running instance of the app. If there's none and app is closed, when I try to open it with my URI scheme it fails to do so.

I must also note that I'm using windows.

Also the project is open source and available at: https://github.com/openmultiplayer/launcher
URI scheme example: `omp-launcher://127.0.0.1:7777`

**Comment by FabianLars** [comment]
I see it flash open for a split second so i assume some of the code at the start of main() panic. If you launch the exe the same way a deep link does, so like this:
```
.\omp-launcher.exe omp-launcher://127.0.0.1:7777
```
You will get this error:
```
error: unexpected argument 'omp-launcher://127.0.0.1:7777' found

Usage: omp-launcher.exe [OPTIONS]

For more information, try '--help'.
```
which stems from the `Args::parse()` line.

The reason why it works while the primary instance is open is because `prepare()` in the secondary instance (spawned by the OS when you call the deep link) forwards the url to your primary instance and exits immediatly, thus never reaching the `Args::parse()` line.

**Comment by AmyrAhmady** [comment]
Glad to know, and thanks for your time you put into it, truly appreciated
